apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    type: local
  name: mongo-pv-vol

spec:
  capacity:
    storage: 1Gi
  storageClassName: manual
  hostPath:
    path: "/mnt/data/mongo"
  accessModes:
    - ReadWriteOnce
    
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongo
  name: mongo-pv-claim

spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi