apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajobs
    tier: backend
  name: karsajobs-be

spec:
  selector:
    app: karsajobs
    tier: backend
  ports:
    - port: 8080
      protocol: TCP
  type: NodePort