apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajobs
    tier: frontend
  name: karsajobs-fe

spec:
  selector:
    app: karsajobs
    tier: frontend
  ports:
    - port: 8000
      protocol: TCP
  type: NodePort